protected/models/Inventario.php
<?php

Yii::import('application.models._base.BaseInventario');

class Inventario extends BaseInventario
{
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
}

protected/controllers/InventarioController.php
<?php

class InventarioController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Inventario'),
		));
	}

	public function actionCreate() {
		$model = new Inventario;


		if (isset($_POST['Inventario'])) {
			$model->setAttributes($_POST['Inventario']);
			
			/*setando situação, campo a principio sem utilidade*/
			$model->situacao = 1;

			/*cria o um novo codigo apartir do numero anterior do acervo sequencial*/
			$acervo = new Acervo;
			$codigo = $acervo->geraCodigo();
			$model->numero_inventario = $codigo;

			$acervo->codigo = $codigo;
			$acervo->descricao = $model->nome;
			$acervo->tipo_acervo_id = 3; /*código na tabela tipo_acervo*/
			$acervo->ativo = $model->ativo;
			$acervo->excluido = $model->excluido;
 
 			if($acervo->save()){	
 				$model->acervo_id = $acervo->id;				
				if ($model->save()) {
					if (Yii::app()->getRequest()->getIsAjaxRequest())
						Yii::app()->end();
					else
						$this->redirect(array('admin'));
				}else{
					$acervo->delete();
				}
			}	
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Inventario');


		if (isset($_POST['Inventario'])) {
			$model->setAttributes($_POST['Inventario']);

			if ($model->save()) {		
				/*atualiza a descrição do acervo*/		
				$acervo = $this->loadModel($model->acervo_id, 'Acervo');
				$acervo->descricao = $model->nome;
				$acervo->save(false);
				$this->redirect(array('admin'));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		$model = $this->loadModel($id, 'Inventario');
		$model->excluido = '1';

		if($model->update(array('excluido'))){
			$this->redirect(array('admin'));
		}
	}

	public function actionClonar($id) {
		$model_original = $this->loadModel($id, 'Inventario');

		/*cria o um novo codigo apartir do numero anterior do acervo sequencial*/
		$acervo = new Acervo;
		$codigo = $acervo->geraCodigo();
		$model_original->numero_inventario = $codigo;

		$acervo->codigo = $codigo;
		$acervo->descricao = $model_original->nome;
		$acervo->tipo_acervo_id = 1; /*código na tabela tipo_acervo*/
		$acervo->ativo = $model_original->ativo;
		$acervo->excluido = $model_original->excluido;

		if($acervo->save()){				
				$model_original->id 		  = null;

				$model = new Inventario;
				$model->setAttributes($model_original->attributes);
				$model->acervo_id = $acervo->id;

			if ($model->save(false)) {				
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect('index.php?r=inventario/update&id='.$model->id);
			}else{				
				$acervo->delete();
			}
		}
	}

	public function actionIndex() {
		$this->actionAdmin();
	}

	public function actionAdmin() {
		$model = new Inventario('search');
		$model->unsetAttributes();

		if (isset($_GET['Inventario']))
			$model->setAttributes($_GET['Inventario']);

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionImagens($id){	

		$model = $this->loadModel($id, 'Inventario');		

		$anexos	= new InventarioImagem();				
		$model->inventarioImagem	= $anexos->getAnexos($id);	

		
		$this->render('_anexos', array(
			'model' => $model,
		));

	}

	public function actionAnexarImagens($id){	

		// verifica se é uma requisão ajax
		if (Yii::app()->getRequest()->getIsAjaxRequest()){
			
			// verifica se o formulário foi submetido
			if(isset($_POST['Inventario'])){

				// instancia a model responsável pela validação dos dados do arquivo
				$inventario = new Inventario();
				
				// defini o cenário para relização das validações
				$inventario->setScenario('upload');

				// captura o arquivos submetido
				$inventario->inventarioImagem = CUploadedFile::getInstance($inventario, 'inventarioImagem');
								
				// valida os dados
				if(!empty($inventario->inventarioImagem) && $inventario->validate(array('inventarioImagem'))){
					
					// inicializa variavel que ira receber os erros encontrados no momento de salvar os arquivos
					$error = null;
					
					// inicializa variavel que ira a mensagem de sucesso quando encontrado
					$success = null;
					
					// instancia model responsável por armazenar o anexo
					$anexo = new InventarioImagem();
					
					// armazena o arquivo e captura os resultados
					$result = $anexo->saveUpload($inventario->inventarioImagem, $id);
					
					// verifica o tipo de resultado gerado
					if(isset($result[InventarioImagem::FILE_ERROR])){
						echo json_encode($result[InventarioImagem::FILE_ERROR]);
					}elseif(isset($result[InventarioImagem::FILE_SUCCESS])){
						echo json_encode($result[InventarioImagem::FILE_SUCCESS]);
					}
				}else{
					$error 	= null;
					$error 	= str_replace('?', '', $inventario->getError('inventarioImagem')); // para garantir que a mensagem de erro ira ser apresentada corretamente nos casos de tipo inválido
					$name	= $inventario->inventarioImagem->getName();
 					$data	= array(compact('error', 'name'));
					echo json_encode($data);					
				}
			}
		}
	}
	
	public function actionExcluirImagem($id){
		
		// verifica se é uma requisão ajax
		if (Yii::app()->getRequest()->getIsAjaxRequest()){
			if (Yii::app()->getRequest()->getIsPostRequest()) {
				
				// captura os dados do arquivo
				$model = $this->loadModel($id, 'InventarioImagem');

				// verifica se o arquivo a ser excuido existe no servidor
				if(file_exists($model->directory.$model->file)){
					// exclui o arquivo do servidor
					unlink($model->directory.$model->file);
					
					// exclui do banco de dados o registro
					$model->delete();
					
				}
				
			}else{
				throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
			}
		}else{
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
		}
	}	

	public function actionImagemDefault() {

		if (isset($_POST['id'])) {
			$model = $this->loadModel($_POST['id'], 'InventarioImagem');
			$model->principal=1;


			if ($model->update()) {
				/*Se colocou a imagem selecionada como principal, coloca as demais como não principal*/
				$id = $model->id;
				$inventario_id = $model->inventario_id;

				$criteria = new CDbCriteria;
				$criteria->addCondition('t.id !='.$id);
				$criteria->addCondition('t.inventario_id ='.$inventario_id);
				$demais_itens = InventarioImagem::Model()->findAll($criteria);

				foreach ($demais_itens as $key => $value) {
					$model2 = $this->loadModel($value->id, 'InventarioImagem');
					$model2->principal=0;
					$model2->update();
				}

				die;

					die('ok');	
			}else{
				die('error');
			}
		}	
	}	


	public function actionPublicarCatalogo() {

		if (isset($_POST['id'])) {
			$model = $this->loadModel($_POST['id'], 'Inventario');

			if($model->catalogo == 1){
				$model->catalogo=0;
			}else{
				$model->catalogo=1;
			}

			if ($model->update()) {
					die('ok');	
			}else{
				die('error');
			}
		}	
	}	

	public function actionRelatorios(){

		if($_POST){			
						
			if($_POST['Inventario']['ativo'] == 2){
				$ativo = '0,1';
			}else{
				$ativo = $_POST['Inventario']['ativo'];
			}


			if($_POST['Inventario']['doador_id'] == ''){
				$doador = Yii::app()->db->createCommand('SELECT id FROM doador where ativo=1 and excluido=0')->queryAll();

				$doadores = array();
				foreach ($doador as $key => $value) {
					array_push($doadores, $value['id']);
				}

				$doador_id = implode(",", $doadores);
			}else{
				$doador_id = $_POST['Inventario']['doador_id'];
			}

			if($_POST['Inventario']['modo_aquisicao_id'] == ''){
				$modo_aquisicao = Yii::app()->db->createCommand('SELECT id FROM modo_aquisicao where ativo=1 and excluido=0')->queryAll();

				$modo_aquisicoes = array();
				foreach ($modo_aquisicao as $key => $value) {
					array_push($modo_aquisicoes, $value['id']);
				}

				$modo_aquisicao_id = implode(",", $modo_aquisicoes);
			}else{
				$modo_aquisicao_id = $_POST['Inventario']['modo_aquisicao_id'];
			}

			if($_POST['Inventario']['acumulado_por_id'] == ''){
				$acumulado_por = Yii::app()->db->createCommand('SELECT id FROM acumulado_por where ativo=1 and excluido=0')->queryAll();

				$acumulados = array();
				foreach ($acumulado_por as $key => $value) {
					array_push($acumulados, $value['id']);
				}

				$acumulado_por_id = implode(",", $acumulados);
			}else{
				$acumulado_por_id = $_POST['Inventario']['acumulado_por_id'];
			}

			if($_POST['Inventario']['tipo_inventario_id'] == ''){
				$tipo_inventario = Yii::app()->db->createCommand('SELECT id FROM tipo_inventario where ativo=1 and excluido=0')->queryAll();

				$tipo_inventarios = array();
				foreach ($tipo_inventario as $key => $value) {
					array_push($tipo_inventarios, $value['id']);
				}

				$tipo_inventario_id = implode(",", $tipo_inventarios);
			}else{
				$tipo_inventario_id = $_POST['Inventario']['tipo_inventario_id'];
			}

			if($_POST['Inventario']['classificacao_id'] == ''){
				$classificacao = Yii::app()->db->createCommand('SELECT id FROM classificacao where ativo=1 and excluido=0')->queryAll();

				$classificacoes = array();
				foreach ($classificacao as $key => $value) {
					array_push($classificacoes, $value['id']);
				}

				$classificacao_id = implode(",", $classificacoes);
			}else{
				$classificacao_id = $_POST['Inventario']['classificacao_id'];
			}

			$colecao_id = $_POST['Inventario']['colecao_id'];


			$sub_colecao = array();
			if($_POST['Inventario']['sub_colecao_id'] == ''){
				$sub_colecao_id = 0;				
			}else{
				$sub_colecao_id = $_POST['Inventario']['sub_colecao_id'];
			}
			array_push($sub_colecao, array('id' => $sub_colecao_id));


			if($_POST['Inventario']['material_id'] == ''){
				$material = Yii::app()->db->createCommand('SELECT id FROM material where ativo=1 and excluido=0')->queryAll();

				$materiais = array();
				foreach ($material as $key => $value) {

protected/views/inventario/_anexos.php
<?php
	Yii::app()->clientScript->registerScript('search', "
			$('.detail-button').click(function(){
				$('.details').toggle();
				return false;
			});
	");
?>
<h2><?php echo 'Imagens Vinculadas ao ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h2>

<div class="alert alert-warning" role="alert">
	<strong>Avisos!&nbsp;</strong><br />
	&rarr;&nbsp;Os anexos devem ser de no máximo <strong>1MB</strong>.<br />
	&rarr;&nbsp;Podem ser anexado no máximo <strong><?php echo Yii::app()->params['maxfileupload'];?> arquivos simultâneos.</strong>.<br />
	&rarr;&nbsp;Arquivos permitidos: <strong><?php echo str_replace('?', '', Yii::app()->params['fileUploadConfig']['PHP']['type']);?></strong>
</div>

<?php 

	$this->widget('booster.widgets.TbFileUpload',
					array(
						'model' 	=> $model,
						'attribute' => 'inventarioImagem',
						'url'		=> $this->createUrl(Yii::app()->controller->getId().'/anexarImagens', array('id' => $model->id)),
						'formView'	=> 'application.views.inventario._formAnexo',
						'multiple' 	=> true,
						'options'	=> array(
							'maxFileSize'		=> Yii::app()->params['fileUploadConfig']['JS']['size'],
							'acceptFileTypes' 	=> 'js:/(\.|\/)('.Yii::app()->params['fileUploadConfig']['JS']['type'].')$/i',
							'maxNumberOfFiles' 	=> Yii::app()->params['maxfileupload'],
							'imageForceResize'	=> true,
						),
					)
	);
	
	$this->renderPartial('_listaAnexos', compact('model'));
	
?>

protected/views/inventario/_formAnexo.php
<?php
/**
 * The file upload form used as target for the file upload widget
 *
 * @var TbFileUpload $this
 * @var array $htmlOptions
 */
?>
<?php echo CHtml::beginForm($this->url, 'post', $this->htmlOptions); ?>
<div class="fileupload-buttonbar">
    <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-info btn-sm fileinput-button">
            <i class="glyphicon glyphicon-plus"></i> 
            <span>Adicionar anexo</span>
            <?php
            if ($this->hasModel()) :
                echo CHtml::activeFileField($this->model, $this->attribute, $htmlOptions) . "\n"; else :
                echo CHtml::fileField($name, $this->value, $htmlOptions) . "\n";
            endif;
            ?>
        </span>
        <!-- 
        <button type="submit" class="btn btn-primary btn-sm start">
            <i class="glyphicon glyphicon-upload"></i>
            <span>Salvar todos anexos</span>
        </button>
        -->
        <button type="reset" class="btn btn-default btn-sm cancel">
            <i class="glyphicon glyphicon-ban-circle"></i>
            <span>Cancelar anexos</span>
        </button>
    </div>
    <div class="span5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active" role="progressbar">
            <div class="bar" style="width:0;"></div>
        </div>
        <!-- The extended global progress information -->
        <div class="progress-extended">&nbsp;</div>
    </div>
</div>
<!-- The loading indicator is shown during image processing -->
<div class="fileupload-loading"></div>
<br>
<!-- The table listing the files available for upload/download -->
<div class="row-fluid">
    <table class="table table-striped">
        <tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
</div>
<?php echo CHtml::endForm(); ?>

protected/views/inventario/_listaAnexos.php
<?php 
// verifica se existe anexos para ata
$list = $model->inventarioImagem->getData();
if(!empty($list)){	
	
	$box = $this->beginWidget('booster.widgets.TbPanel',
				array(	'title' => InventarioImagem::label(2),
						'headerIcon' => 'glyphicon glyphicon-picture',
						'padContent' => false,
						'htmlOptions' => array('class' => 'bootstrap-widget-table table-responsive'),
				)
	);
		$this->widget('booster.widgets.TbExtendedGridView', array(
				'id' 				=> 'anexos-grid',
				'type'				=> 'striped bordered condensed hover',
				'htmlOptions'		=> array('class' => 'responsive'),
				'enablePagination' 	=> true,
				'template' 			=> "{items}\n{pager}\n{summary}",
				'summaryText' 		=> false,
				'dataProvider' 		=> $model->inventarioImagem,
				'columns' 			=>
				array(
					array(
          			   	   'name'=>'file',
            			   'type'=>'html',
            			   'value'=>'(file_exists("images/tridimensional/".$data->file))?CHtml::image("images/tridimensional/".$data->file,"",array("style"=>"width:70px;height:70px;"))
            			   																:CHtml::image("images/imagem_indisponivel.JPG","",array("style"=>"width:70px;height:70px;"))',
 
        			),
					array(
							'name'				=> 'nome_arquivo',
							'headerHtmlOptions'	=> array('class'=>'col-sm-6 text-left'),
							'htmlOptions' 		=> array('class'=>'text-left'),
							'type'				=> 'raw',
							'value'				=> '$data->nome_arquivo',
					),
					array(
							'name'				=> 'data_criacao',
							'headerHtmlOptions'	=> array('class'=>'col-sm-2 text-left'),
							'htmlOptions' 		=> array('class'=>'text-left'),
							'value'				=> '$data->data_criacao',
					),
					array(
							'header' 			=> Yii::t('ses', 'Ações'),
							'class'				=> 'booster.widgets.TbButtonColumn',
							'template'			=> '{ativa}{desativa} | {download} | {delete}',
							'headerHtmlOptions'	=> array('class'=>'col-sm-4 text-center'),
							'htmlOptions'		=> array('style' => 'vertical-align: middle', 'class' => 'text-center'),
							'buttons'			=> array(
					                'ativa'=>array(
					                    'url' => '$data->id',
					                    'icon'=>'glyphicon glyphicon-star-empty',
						                'options'=>array('style'=>'color:red;'),
					                    'click' => "function( e ){e.preventDefault();  imagemDefault( $( this ).attr( 'href' ) ,'inventario', 'anexos-grid'); }",
					                    'visible'=>'$data->principal==0?1:0',
					                    'label'=>'Não Principal'
					                ),
					                'desativa'=>array(
					                    'url' => '$data->id',
					                    'icon'=>'glyphicon glyphicon-star',
						                'options'=>array('style'=>'color:green;'),
					                    'click' => "function( e ){e.preventDefault();  imagemDefault( $( this ).attr( 'href' ) ,'inventario', 'anexos-grid'); }",
					                    'visible'=>'$data->principal==1?1:0',
					                    'label'=>'Principal'
					                ),									
									'download'	=> array(
										'label'	=> '<span class="glyphicon glyphicon-cloud-download"></span>&nbsp;',
										'url'     => '$data->directory.$data->file',
										'options' => array(
												'title'		=> 'Download',
												'class'		=> 'download',
												'rel'		=> 'gallery',
												'download'	=> 'download',
										),
									),
									'delete'	=> array(
										'url'	=>	'Yii::app()->createUrl("inventario/excluirImagem", array("id"=>$data->id))'
									),
							),
					),
				),
		));
	$this->endWidget();
}
?>

protected/views/inventario/admin.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Manage',
);

$this->title_action = GxHtml::encode($model->label(2));

Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('inventario-grid', {
		data: $(this).serialize()
	});
	return false;
});

");

$this->widget(
    'booster.widgets.TbButtonGroup',
    array(
        'buttons' => array(
            array(
                'buttonType'    => 'link',
                'label'         => 'Cadastrar Novo '.$model->label(),
                'url'           => array('create'),
                'context'       => 'primary'
            ),
        ),
    )
);

?>




<?php $this->widget('booster.widgets.TbExtendedGridView', array(
	'id' => 'inventario-grid',
	'type' => 'striped bordered condensed hover',
	'dataProvider' => $model->search(),
	'filter' => $model,
    'pager' => array(
        'class' => 'booster.widgets.TbPager', // **use extended CLinkPager class**
        'cssFile' => false, //prevent Yii autoloading css
        'header' => false, // hide 'go to page' header
        'firstPageLabel' => '&lt;&lt;', // change pager button labels
        'prevPageLabel' => '&lt;',
        'nextPageLabel' => '&gt;',
        'lastPageLabel' => '&gt;&gt;',
        'displayFirstAndLast' => true,
    ),
	'columns' => array(	
		'numero_inventario',
		'numero_anterior',		
		'nome',
		array(
				'name'      => 'colecao_id',
				'value'     => 'GxHtml::valueEx($data->colecao)',				
				'filter'    => GxHtml::listDataEx(Colecao::model()->findAllAttributes(null, true)),
		),
		array(
				'name'      => 'sub_colecao_id',
				'value'     => 'GxHtml::valueEx($data->subColecao)',				
				'filter'    => GxHtml::listDataEx(SubColecao::model()->findAllAttributes(null, true)),
		),				
		array(
			'name'           =>'ativo',
			'value'          =>'UtilModel::statusAtual($data->ativo)',
			'filter'         => array('1'=>'Ativo','0'=>'Inativo'),
			'htmlOptions'    => array('style'=>'width:5%;')

		),				
		array(
			'header' 		=> Yii::t('ses', 'Ações'),
			'class'			=> 'booster.widgets.TbButtonColumn',
			'template'		=> '{desdobramento_sim}{desdobramento_nao} | {imagens_sim}{imagens_nao} | {update} | {view} | {publicar}{despublicar} | {delete}|{clonar}',
			'buttons'=>array(
                'desdobramento_sim'=>array(
                    'url'       => 'Yii::app()->createUrl("desdobramento/", array("id"=>$data->id))',
                    'icon'      => 'glyphicon glyphicon-menu-hamburger',
                    'options'   => array('class'=>'view','style'=>'color:green;'),
                    'label'     => 'Desdobramento',
                    'visible'   => '$data->desdobramentos!=null?1:0'
                ),			
                'desdobramento_nao'=>array(
                    'url'       => 'Yii::app()->createUrl("desdobramento/", array("id"=>$data->id))',
                    'icon'      => 'glyphicon glyphicon-menu-hamburger',
                    'options'   => array('class'=>'view','style'=>'color:red;'),
                    'label'     => 'Desdobramento',
                    'visible'   => '$data->desdobramentos==null?1:0'
                ),			                
                'imagens_sim'=>array(
                    'url'       => 'Yii::app()->createUrl("inventario/imagens/", array("id"=>$data->id))',
                    'icon'      => 'glyphicon glyphicon-picture',
                    'options'   => array('class'=>'view','style'=>'color:green;'),
                    'label'     => 'Contém Imagens Cadastradas',
                    'visible'   => '$data->inventarioImagem!=null?1:0'
                ),
                'imagens_nao'=>array(
                    'url'       => 'Yii::app()->createUrl("inventario/imagens/", array("id"=>$data->id))',
                    'icon'      => 'glyphicon glyphicon-picture',
                    'options'   => array('class'=>'view','style'=>'color:red;'),
                    'label'     => 'Não Contém Imagens Cadastradas',
                    'visible'   => '$data->inventarioImagem==null?1:0'
                ),                			                
                'update'=>array(                    
                    'label'=>'Editar',
                ),                                          
                'view'=>array(                    
                    'label'=>'Visualizar',
                ),
                'publicar'=>array(
                    'url'       => '$data->id',
                    'icon'      => 'glyphicon glyphicon-globe',
	                'options'   => array('style'=>'color:red;'),
                    'click'     => "function( e ){e.preventDefault();  publicarCatalogo( $( this ).attr( 'href' ) ,'inventario', 'inventario-grid'); }",
                    'label'     => 'Não Publicado no Site',
                    'visible'   => '$data->catalogo==0?1:0'
                ),
                'despublicar'=>array(
                    'url'       => '$data->id',
                    'icon'      => 'glyphicon glyphicon-globe',
	                'options'   => array('style'=>'color:green;'),
                    'click'     => "function( e ){e.preventDefault();  publicarCatalogo( $( this ).attr( 'href' ) ,'inventario', 'inventario-grid' ); }",
                    'label'     => 'Publicado no Site',
                    'visible'   => '$data->catalogo==1?1:0'
                ),                
                'delete'=>array(                    
                    'label'=>'delete',
                ),
                'clonar'=>array(
                    'url'=> 'Yii::app()->createUrl("inventario/clonar", array("id"=>$data->id))',
                    'icon'=>'glyphicon glyphicon-copy',
                    'options'=>array('class'=>'view'),
                    'label'=>'Clonar',
                ),                  
    		),
			'headerHtmlOptions'	=> array(
                'class'=>'col-sm-1 text-center'
            ),
			'htmlOptions'	=> array(
                'style' => 'vertical-align: middle; width:30%;',
                'class' => 'text-center'
            ),
		),
	),
)); ?>

protected/views/inventario/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	'Create',
);

$this->menu = array(
	array('label'=>'List' . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>'Manage' . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo 'Criar' . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/views/inventario/update.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	'Update',
);

$this->menu = array(
	array('label' => 'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => 'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => 'View' . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => 'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo 'Alterar' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model));
?>

protected/views/inventario/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model) => array('view', 'id' => GxActiveRecord::extractPkValue($model, true)),
	'Update',
);

$this->menu = array(
	array('label' => 'List' . ' ' . $model->label(2), 'url'=>array('index')),
	array('label' => 'Create' . ' ' . $model->label(), 'url'=>array('create')),
	array('label' => 'View' . ' ' . $model->label(), 'url'=>array('view', 'id' => GxActiveRecord::extractPkValue($model, true))),
	array('label' => 'Manage' . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo 'Visualizar' . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_formView', array(
		'model' => $model));
?>